// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#nullable disable

using System.Drawing;

namespace System.Windows.Forms.Tests;

public class ToolStripDropDownMenuTests
{
    [WinFormsFact]
    public void ToolStripDropDownMenu_Constructor()
    {
        using ToolStripDropDownMenu menu = new();

        Assert.NotNull(menu);
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ConstructorOwnerItemBool()
    {
        using ToolStripButton owner = new();
        bool isAutoGenerated = true;

        using ToolStripDropDownMenu menu = new(owner, isAutoGenerated);

        Assert.NotNull(menu);
        Assert.Equal(owner, menu.OwnerItem);
        Assert.True(menu.IsAutoGenerated);
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_Break_ItemItselfStartsNewColumn()
    {
        // Regression test: a ToolStripMenuItem with Break = true must become the first item of a new
        // column (mirroring native MFT_MENUBREAK semantics), not the last item of the previous column.
        using ToolStripDropDownMenu menu = new();
        ToolStripMenuItem item1 = new("Item1");
        ToolStripMenuItem item2 = new("Item2");
        ToolStripMenuItem item3 = new("Item3") { Break = true };
        ToolStripMenuItem item4 = new("Item4");

        menu.Items.AddRange([item1, item2, item3, item4]);
        menu.Show(new Point(0, 0));

        try
        {
            // item1 and item2 remain together in the first column.
            Assert.Equal(item1.Bounds.X, item2.Bounds.X);
            Assert.True(item2.Bounds.Y > item1.Bounds.Y);

            // item3 requested the break, so it -- not item4 -- must start the new column:
            // its X moves to a new column, and its Y resets to the top (same row as item1).
            Assert.True(item3.Bounds.X > item2.Bounds.X);
            Assert.Equal(item1.Bounds.Y, item3.Bounds.Y);

            // item4 follows item3 within that same new column.
            Assert.Equal(item3.Bounds.X, item4.Bounds.X);
            Assert.True(item4.Bounds.Y > item3.Bounds.Y);
        }
        finally
        {
            menu.Close();
        }
    }
}
